import 'package:audioplayers/audioplayers.dart';

/// Sound categories (section 40). Grouped the same way a future
/// `AudioManager` would mix/mute them independently (music, ambience, ui,
/// battle, dice, achievement, discovery).
enum SoundEvent {
  diceRoll,
  battleImpact,
  territoryConquered,
  cardDraw,
  achievementUnlocked,
  bibleDiscovery,
  uiTap,
}

/// Abstraction over audio playback. UI/animation code calls this and never
/// touches a concrete audio package directly, so swapping these
/// synthesized placeholder effects for professionally produced assets
/// later only means replacing files under `assets/audio/` — never a
/// change to call sites.
abstract class AudioService {
  void play(SoundEvent event);

  /// Master on/off (section 41 "efeitos sonoros off"). Muting stops any
  /// in-flight sound and makes further `play` calls no-ops until unmuted.
  void setMuted(bool muted);
}

const Map<SoundEvent, String> _assetPaths = {
  SoundEvent.diceRoll: 'audio/dice_roll.wav',
  SoundEvent.battleImpact: 'audio/battle_impact.wav',
  SoundEvent.territoryConquered: 'audio/territory_conquered.wav',
  SoundEvent.cardDraw: 'audio/card_draw.wav',
  SoundEvent.achievementUnlocked: 'audio/achievement_unlocked.wav',
  SoundEvent.bibleDiscovery: 'audio/bible_discovery.wav',
  SoundEvent.uiTap: 'audio/ui_tap.wav',
};

/// Plays the bundled sound effects (`assets/audio/*.wav`, generated by a
/// synthesis script — see TASKS.md — not studio-recorded). Each call gets
/// its own short-lived `AudioPlayer` so overlapping sounds (e.g. UI taps
/// during a dice roll) never cut each other off; `audioplayers` disposes
/// low-latency players cheaply enough that this is fine for short SFX.
class AssetAudioService implements AudioService {
  bool _muted = false;

  @override
  void setMuted(bool muted) => _muted = muted;

  @override
  void play(SoundEvent event) {
    if (_muted) return;
    final path = _assetPaths[event];
    if (path == null) return;
    final player = AudioPlayer();
    player.play(AssetSource(path));
    // Fire-and-forget: release this player's resources once it naturally
    // finishes, without blocking the caller or needing a managed pool.
    player.onPlayerComplete.listen((_) => player.dispose());
  }
}

/// Used only where no `BuildContext`/widget tree exists to own an
/// `AssetAudioService` (e.g. pure-Dart tests) — keeps every call site
/// wired without pulling the audio plugin into test runs that don't need it.
class NoOpAudioService implements AudioService {
  @override
  void play(SoundEvent event) {}

  @override
  void setMuted(bool muted) {}
}
